### ISSUE TITLE
eslint and plugins should be listed as peerDependencies

### ISSUE THREAD

**Issue by smcphail** [oclif/eslint-config-oclif#113]
**Describe the bug**
Per [Publishing a Shareable Config](https://eslint.org/docs/latest/extend/shareable-configs#publishing-a-shareable-config).  The eslint plugins (`n`, `mocha` and `unicorn`) and `eslint` should be listed as `peerDependencies` in `package.json`.  ESLint needs to be able to resolve them from the project root but depending on the project config/other dependencies they may not be hoisted during install.  Installing as peers resolves that (tested using a local copy of the repo, modified `package.json` and installed with `--install-links` option).

**To Reproduce**
I'm not sure exactly what causes dependencies not to be hoisted but it seems sometimes they aren't.   You can force a nested install to see the issue:
```shell
% rm -rf node_modules package-lock.json
% npm install --install-strategy nested
% eslint --ext .ts,.js,.cjs,.mjs --config .eslintrc .


Oops! Something went wrong! :(
```

**Expected behavior**
Installing `eslint-config-oclif` should include the necessary plugins automatically.

**Screenshots**
This output is typical of the issue.
```shell
Oops! Something went wrong! :(

ESLint: 8.57.0

ESLint couldn't find the plugin "eslint-plugin-unicorn".

(The package "eslint-plugin-unicorn" was not found when loaded as a Node module from the directory "/Users/username/project_root".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-unicorn@latest --save-dev

The plugin "eslint-plugin-unicorn" was referenced from the config file in "--config » eslint-config-oclif".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

**Environment (please complete the following information):**

- OS & version: Darwin HOSTNAME 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64
- Shell/terminal & version: zsh 5.9 (x86_64-apple-darwin23.0)

**Additional context**
[Publishing a Shareable Config](https://eslint.org/docs/latest/extend/shareable-configs#publishing-a-shareable-config)

**Comment by mdonnalley** [comment]
See my comment here: https://github.com/oclif/eslint-config-oclif-typescript/issues/128#issuecomment-2023036291
